export const venuesInputFields = [
  {
    label: "Name",
    name: "name",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Location",
    name: "location",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Address",
    name: "address",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Longitude ",
    name: "longitude",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Latitude",
    name: "latitude",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Google map embed code",
    name: "googleMapEmbedCode",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Block alias",
    name: "blockAlias",
    columnWidthLg: 6,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Blocks alias",
    name: "blocksAlias",
    columnWidthLg: 6,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Row alias",
    name: "rowAlias",
    columnWidthLg: 6,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Rows alias",
    name: "rowsAlias",
    columnWidthLg: 6,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Seat alias",
    name: "seatalias",
    columnWidthLg: 6,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Seats alias",
    name: "seatsalias",
    columnWidthLg: 6,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Table alias",
    name: "tablealias",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Tables alias",
    name: "tablesalias",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
  {
    label: "Basic standard plan",
    name: "basicStandardPlan",
    columnWidthLg: 4,
    columnWidthsm: 6,
    columnWidthxs: 12,
  },
]
